development:
  adapter: postgresql
  encoding: unicode
  database: facebookCam_development
  pool: 5
  username: facebookCam
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: facebookCam_test
  pool: 5
  username: facebookCam
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: facebookCam_production
  pool: 5
  username: facebookCam
  password:
