development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

#development:
#  adapter: postgresql
#  encoding: unicode
#  database: facebookCam_development
#  pool: 5
#  username: facebookCam
#  password:

test:
  adapter: postgresql
  encoding: unicode
  database: facebookCam_test
  pool: 5
  username: facebookCam
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: facebookCam_production
  pool: 5
  username: facebookCam
  password:
